// <auto-generated />
using System;
using LupiraGeoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LupiraGeoApi.Data.Migrations
{
    [DbContext(typeof(GeoDbContext))]
    [Migration("20260709144741_InitialGeo")]
    partial class InitialGeo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("geo")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LupiraGeoApi.Domain.AdminArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Point>("Centroid")
                        .HasColumnType("geography (Point, 4326)");

                    b.Property<long?>("GeonamesId")
                        .HasColumnType("bigint");

                    b.Property<string>("IsoCode")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WithinAreaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Centroid");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "gist");

                    b.HasIndex("GeonamesId")
                        .IsUnique();

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("WithinAreaId");

                    b.ToTable("AdminAreas", "geo");
                });

            modelBuilder.Entity("LupiraGeoApi.Domain.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("FormattedAddress")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (Point, 4326)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("WithinAreaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CanonicalName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("CanonicalName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Category");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("WithinAreaId");

                    b.ToTable("Places", "geo");
                });

            modelBuilder.Entity("LupiraGeoApi.Domain.PlaceAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Lang")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PlaceId");

                    b.ToTable("PlaceAliases", "geo");
                });

            modelBuilder.Entity("LupiraGeoApi.Domain.PlaceExternalId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("Scheme", "Value")
                        .IsUnique();

                    b.ToTable("PlaceExternalIds", "geo");
                });

            modelBuilder.Entity("LupiraGeoApi.Domain.AdminArea", b =>
                {
                    b.HasOne("LupiraGeoApi.Domain.AdminArea", "WithinArea")
                        .WithMany()
                        .HasForeignKey("WithinAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("WithinArea");
                });

            modelBuilder.Entity("LupiraGeoApi.Domain.Place", b =>
                {
                    b.HasOne("LupiraGeoApi.Domain.AdminArea", "WithinArea")
                        .WithMany()
                        .HasForeignKey("WithinAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WithinArea");
                });

            modelBuilder.Entity("LupiraGeoApi.Domain.PlaceAlias", b =>
                {
                    b.HasOne("LupiraGeoApi.Domain.Place", null)
                        .WithMany("Aliases")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LupiraGeoApi.Domain.PlaceExternalId", b =>
                {
                    b.HasOne("LupiraGeoApi.Domain.Place", null)
                        .WithMany("ExternalIds")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LupiraGeoApi.Domain.Place", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("ExternalIds");
                });
#pragma warning restore 612, 618
        }
    }
}
